spring.application.name=ProjetoAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/ProjetoAPI
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html